### ISSUE TITLE
Publish Notifier Not Displaying

### ISSUE THREAD

**Issue by jordanpowell88** [dalibormesaric/PublishNotifier#1]
I installed the extension and created the incoming slack webhook but I am not able to get the publish notifier to display. The way I understand it based upon the documentation is that it should appear after the publish has completed but nothing is happening? Not sure what I'm doing incorrectly.

Im using VS 2017 Professional on Windows 10. Is their a way to edit this setting manually?

**Comment by dalibormesaric** [comment]
Hi Jordan! Do you see the extension under Tools > Extensions and Updates as installed? You need to restart VS after installing if it is not there.

**Comment by jordanpowell88** [comment]
Yes and I've done a restart...any thoughts? 
![2018-01-05 12_49_52-vacant - microsoft visual studio](https://user-images.githubusercontent.com/3605268/34621421-12c7886e-f217-11e7-931a-85a5af773db6.png)

**Comment by dalibormesaric** [comment]
Hmm, I just tried installing again and publishing a new WebApplication template project in to a folder and it works as it is described. Can you try the same scenario?

![image](https://user-images.githubusercontent.com/1780620/34621848-0d52f146-f24b-11e7-945a-c4bf183070bd.png)

Or maybe try browsing your windows using Alt-Tab when you see this in case the dialog box is not in focus:

![image](https://user-images.githubusercontent.com/1780620/34621930-50654b00-f24b-11e7-96e8-cd110b549a1f.png)

**Comment by jordanpowell88** [comment]
I uninstalled and re-installed it like you suggested and published again with no luck.

![image](https://user-images.githubusercontent.com/3605268/34623416-529446fa-f21f-11e7-8a3a-3b73c6ff70fa.png)

**Comment by dalibormesaric** [comment]
I tried installing it on few other computers, but it works every time... I'll keep testing, but in the mean time, can you try this: https://blogs.msdn.microsoft.com/visualstudio/2010/02/24/troubleshooting-extensions-with-the-activity-log/ and see it you get any errors

**Comment by dylanvdmerwe** [comment]
This should be reopened. 

1) No popup after publishing a .NET 5 ASP API.
2) No instructions on how to configure the webhook URL in the json manually.

**Comment by dalibormesaric** [comment]
Hey @dylanvdmerwe ! I'm really sorry but I can't reproduce the issue, at least not with the amount of information that I have. Json file should be in the root of your solution, but I guess if the extension is not working then it is not created there.

I just tested again on two computers with a new .net 5 web api project, publishing both to a folder and to a web app in azure, and extension works as expected.

I have added instructions on how to run the extension in debug mode https://github.com/dalibormesaric/PublishNotifier/blob/master/SETUP.md in case you are willing to provide some help in chasing down this bug :)

**Comment by dylanvdmerwe** [comment]
Of course I will help track it down and assist. 

Firstly, this is VS 2019 16.8.4.

You will need to guide me more on how to do [this](https://github.com/dalibormesaric/PublishNotifier/blob/master/SETUP.md). I do not see the options anywhere in my project?

![image](https://user-images.githubusercontent.com/2852839/107411610-694ce900-6b17-11eb-8f90-fc5ffbe60a7f.png)

**Comment by dalibormesaric** [comment]
Great! Frist you will need to add Visual Studio extension development workload in your visual studio installer by clicking on Modify, then you need to clone PublishNotifier repository and follow the instructions I mentioned above. When you run the extension in debug mode, it will open an experimental instance of visual studio where you can open your web project and try publishing it. [More information](https://docs.microsoft.com/en-us/visualstudio/extensibility/extensibility-hello-world?view=vs-2019#run-it)

**Comment by dylanvdmerwe** [comment]
@dalibormesaric sorry for the delay. 

I am running the debug PublishNotifier with my solution open. 

I then try to publish the project as per the normal process. The publish occurred successfully but no extension popup. 

After publish the following exception was raised by PublishNotifier instance:

![image](https://user-images.githubusercontent.com/2852839/108596314-e0427700-738c-11eb-82c4-a74159e9fdad.png)

Path value is: `C:\Projects\WunderlustAPI\WebService.SiteApi\PublishNotifier.json` but it looks wrong. There's a folder missing. 

![image](https://user-images.githubusercontent.com/2852839/108609375-1eb05400-73d6-11eb-9d60-bebfec1f35c2.png)


I think you should rather identify where the .sln file is and write the `PublishNotifier.json` file there right so there is one config per solution? Or is there one config per project? My solutions are heavily split up into folders:

![image](https://user-images.githubusercontent.com/2852839/108596390-619a0980-738d-11eb-9d67-98ceb094e60e.png)

Inside WebServiceProjects dir, there is a WebService.SiteApi dir inside which the the project. In this specific solution there are a few publishable projects:
![image](https://user-images.githubusercontent.com/2852839/108596421-9017e480-738d-11eb-93bf-7510be8d06de.png)

Please let me know if I can assist further.

**Comment by dalibormesaric** [comment]
Wow, thank you so much for your report! I was able to recreate the issue, and it was due to having projects in one more level of directories. The way I constructed the project path was wrong, and it should be fixed now.

I published a new version to marketplace https://marketplace.visualstudio.com/items?itemName=dalibormesaric.PublishNotifier , so please give it a try and let me know if this is fixed now.

Thanks again @dylanvdmerwe  ! Hopefully this fixes the original issue for @jordanpowell88 as well :)

I wrote some ideas on what could be added to the extension here https://github.com/dalibormesaric/PublishNotifier/blob/master/CHANGELOG.md and if you think some would bring value to you, please open an issue and I'll do it.

**Comment by dylanvdmerwe** [comment]
You are a star! Love your work and look forward to using the extension!
